export const WEEKDAY_INDEXES = {
  SUNDAY: 0,
  MONDAY: 1,
  TUESDAY: 2,
  WEDNESDAY: 3,
  THURSDAY: 4,
  FRIDAY: 5,
  SATURDAY: 6,
} as const;

export const WEEKDAY_ONLY_INDEXES = [
  WEEKDAY_INDEXES.MONDAY,
  WEEKDAY_INDEXES.TUESDAY,
  WEEKDAY_INDEXES.WEDNESDAY,
  WEEKDAY_INDEXES.THURSDAY,
  WEEKDAY_INDEXES.FRIDAY,
] as const;
